name: CI/CD Deployment to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: "australia-weather"
  GKE_REGION: "us-central1"
  DEPLOYMENT_NAME: "mlops-app"
  REPOSITORY: "us-central1-docker.pkg.dev/prime-hydra-459309-g4/my-repo"
  IMAGE: "us-central1-docker.pkg.dev/prime-hydra-459309-g4/my-repo/mlops-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    container:
      image: google/cloud-sdk:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud and Docker
        run: |
          gcloud config set project $PROJECT_ID
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -f kubernetes-deployment.yaml
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA